MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/gpu/.cache/torch/checkpoints/jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('1')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [12, 12]
  SIE_CAMERA: True
  SIE_COE: 3.0
  JPM: True
  RE_ARRANGE: True
  RES_TRI_NUM: 0
  RESOLUTION_LOSS_WEIGHT: 0.10
  RES_DEEPCOPY: True
  CAT_RES_FEAT: False

  ONLY_RES: True

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('MLR_DukeMTMC')
  ROOT_DIR: ('/mnt/data/datasets/DukeMTMC-reID/degradation_uni_1_4')

DATALOADER:
  SAMPLER: 'rmse_softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.004
  IMS_PER_BATCH: 64
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 120
  LOG_PERIOD: 50
  EVAL_PERIOD: 120
  START_EVAL: 120
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
#  WEIGHT: '/mnt/data/code/reidlog_3/MLR_Market1501/degradation_uni_1_4/changemos/resloss0_010_lr0_003_120epoch/2023-06-09-20-19-02/transformer_best_Rank1'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  EVAL_RESOLUTION: True
#  WEIGHT: '/mnt/data/code/reidlog_3/MLR_Duke/changemos/lossres0_010_lr003_120epoch_NoResFeat/2023-06-05-20-32-24/transformer_120.pth'
  WEIGHT: '/mnt/data/code/reidlog_3/MLR_Duke/changemos/lambda01_ONLYRes_lr0004/2023-07-08-10-27-12/transformer_best_Rank1'



OUTPUT_DIR: '/mnt/data/code/reidlog_3/MLR_Duke/changemos/lambda01_ONLYRes_lr0004'

